package ipl.manager.pojo;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.username
     *
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.password
     *
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.email
     *
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.regist_time
     *
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    private Date registTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.login_time
     *
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.last_login_time
     *
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.login_count
     *
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    private Integer loginCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.last_pay_time
     *
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    private Date lastPayTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.pay_time
     *
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.expire_time
     *
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.identity
     *
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    private Short identity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.username
     *
     * @return the value of user_info.username
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.username
     *
     * @param username the value for user_info.username
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.password
     *
     * @return the value of user_info.password
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.password
     *
     * @param password the value for user_info.password
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.email
     *
     * @return the value of user_info.email
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.email
     *
     * @param email the value for user_info.email
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.regist_time
     *
     * @return the value of user_info.regist_time
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public Date getRegistTime() {
        return registTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.regist_time
     *
     * @param registTime the value for user_info.regist_time
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public void setRegistTime(Date registTime) {
        this.registTime = registTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.login_time
     *
     * @return the value of user_info.login_time
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.login_time
     *
     * @param loginTime the value for user_info.login_time
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.last_login_time
     *
     * @return the value of user_info.last_login_time
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.last_login_time
     *
     * @param lastLoginTime the value for user_info.last_login_time
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.login_count
     *
     * @return the value of user_info.login_count
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.login_count
     *
     * @param loginCount the value for user_info.login_count
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.last_pay_time
     *
     * @return the value of user_info.last_pay_time
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public Date getLastPayTime() {
        return lastPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.last_pay_time
     *
     * @param lastPayTime the value for user_info.last_pay_time
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public void setLastPayTime(Date lastPayTime) {
        this.lastPayTime = lastPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.pay_time
     *
     * @return the value of user_info.pay_time
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.pay_time
     *
     * @param payTime the value for user_info.pay_time
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.expire_time
     *
     * @return the value of user_info.expire_time
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.expire_time
     *
     * @param expireTime the value for user_info.expire_time
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.identity
     *
     * @return the value of user_info.identity
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public Short getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.identity
     *
     * @param identity the value for user_info.identity
     * @mbg.generated Thu Mar 22 15:04:16 CST 2018
     */
    public void setIdentity(Short identity) {
        this.identity = identity;
    }
}